# Custom schema file for fork-specific migrations
# Generated automatically by db:schema:dump:custom
# DO NOT EDIT THIS FILE DIRECTLY
#
# This file documents the schema for custom business-specific tables
# that are separate from upstream Chatwoot tables.
#
# Current custom migration version: 20250701233536

ActiveRecord::Schema[7.1].define(version: 20_250_701_233_536) do
  enable_extension 'pgcrypto'

  create_table :account_prompts, id: :uuid, default: -> { 'gen_random_uuid()' }, force: :cascade do |t|
    t.integer :account_id
    t.string :prompt_key, null: false
    t.text :text, null: false
    t.datetime :created_at, null: false
    t.datetime :updated_at, null: false
  end

  add_index :account_prompts, [:account_id], name: 'index_account_prompts_on_account_id'
  add_index :account_prompts, [:account_id, :prompt_key], name: 'index_account_prompts_on_account_id_and_prompt_key', unique: true

  create_table :knowledge_bases, id: :uuid, default: -> { 'gen_random_uuid()' }, force: :cascade do |t|
    t.integer :account_id, null: false
    t.string :name
    t.integer :source_type
    t.string :url
    t.datetime :created_at, null: false
    t.datetime :updated_at, null: false
  end

  add_index :knowledge_bases, [:account_id], name: 'index_knowledge_bases_on_account_id'

  add_foreign_key 'account_prompts', 'accounts'
  add_foreign_key 'knowledge_bases', 'accounts'
end
